### ISSUE TITLE
Function fails at runtime not build time

### ISSUE THREAD

**Issue by tcharding** [Kixunil/hex_lit#1]
Contrary to the code comment this function fails at run time not at compile time.

```rust
// This version makes an out-of-bounds accesses to an array to trigger compilation failure.
#[cfg(all(not(rust_v_1_57), rust_v_1_46))]
#[track_caller]
const fn invalid_digit(digit: u8) {
    let digit = digit as usize;
    #[allow(unknown_lints)]
    #[allow(unconditional_panic)]
    // We add 10000 to ensure it will panic for any digit, we want to use digit in the expression
    // to display the number even though the message is messy.
    let _invalid_digit = [(); 0][digit + 10000];
}
```

Can be verified by putting this into a `main.rs`:
```rust
fn main() {
    invalid_digit('x' as u8);
}

const fn invalid_digit(digit: u8) {
    let digit = digit as usize;
    let _invalid_digit_used_as_array_index = [(); 0][digit + 1000];
}
```

Also the `+ 1000` is unnecessary, accessing `array[0]` of an empty array is still out-of-bounds.

**Comment by tcharding** [comment]
I'm totally wrong about the compile time thing, sorry for the noise.

**Comment by tcharding** [comment]
I worked out my mistake because I cannot get the `invalid_digit` method for `rust_v_1_57` to be called. I keep getting
```
cargo build                                                                                                                                                                   ✘ 101 
   Compiling play v0.1.0 (/home/tobin/build/play)
error[E0080]: evaluation of constant value failed
 --> src/main.rs:6:13
  |
6 |     let _ = hex!("ffxx");
  |             ^^^^^^^^^^^^ the evaluated program panicked at 'invalid hex digit: ASCII 120', src/main.rs:6:13
```

But this works as expected, not sure whats going on.
```rust
pub fn testing() {
    if cfg!(rust_v_1_46) {
        println!("enabled: cfg(rust_v_1_46)");
    }
    if cfg!(rust_v_1_57) {
        println!("enabled: cfg(rust_v_1_57)");
    }
}
```

(I removed `no_std` to get access to `println` obviously)

**Comment by tcharding** [comment]
All this was done while doing a crev review for this crate - done and published!

**Comment by Kixunil** [comment]
> the evaluated program panicked at 'invalid hex digit: ASCII 120

This is literally caused by the function *being* called. :)

> Also the `+ 1000` is unnecessary,

~~It's actually a trick to allow people to read the ASCII value of the invalid digit in the error message - just subtract 1000 (which is trivial since the value is in decimal).~~

Oh, I realized what you mean, good point!
