### ISSUE TITLE
Useage of underscore

### ISSUE THREAD

**Issue by tcharding** [Kixunil/hex_lit#2]
Ugh @Kixunil you used `hex_lit` instead of `hex-lit` in the repo and crate name. This is what happened with `bitcoin_hashes` and turned out to be a PITA.

Raising an issue and closing it immediately just to flag it and provide a historical record. Feel free to slap me next time you see me :)

**Comment by tcharding** [comment]
Closing ...

**Comment by Kixunil** [comment]
Honestly, I mostly don't like hypens in crate names because the `Cargo.toml` becomes inconsistent with `*.rs`.

**Comment by tcharding** [comment]
Fair point, I guess perfect uniformity is just a dream.
